language: java
jdk: openjdk11
services: mongodb
before_install:
  - chmod +x gradlew
before_script:
  - sleep 15
  - mongo exbookDB_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'