spring:
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

retrofit-services:
  services:
    google-books:
      url: https://www.googleapis.com/books/v1/
