spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kurs
      username: admin
      password: password
  jpa:
    show-sql: true

server:
  port: 8082

jwt:
  expirationTime: 36000000
  secret: adlihwu23yfh82gf7243gf234f23

logging:
  level:
    pl:
      exbook:
        DEBUG
