spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
      database: ${DATABASE_NAME}
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
      enabled: true

server:
  port: ${SERVER_PORT}

jwt:
  expirationTime: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET}

logging:
  level:
    pl:
      exbook:
        INFO
