spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
      database: ${DATABASE_NAME}
  jpa:
    show-sql: false

server:
  port: ${SERVER_PORT}

jwt:
  expirationTime: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET}

logging:
  level:
    pl:
      exbook:
        INFO
