spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 111
      database: exbookDB_int
      username: root_int
      password: password_int

jwt:
  expirationTime: 604800000
  secret: integration_tests_jwt_secret
