spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kurs
      username: admin
      password: password

server:
  port: 8082

jwt:
  expirationTime: 3600000
  secret: adlihwu23yfh82gf7243gf234f23
