spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: exbookDB_local
      username: root
      password: password
  jpa:
    show-sql: true

server:
  port: 8082

jwt:
  expirationTime: 36000000
  secret: jwt-secret

logging:
  level:
    pl:
      exbook:
        DEBUG

retrofit-services:
  services:
    google-books:
      url: https://www.googleapis.com/books/v1/
