name: CI
on: push

jobs:
  run_tests:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and test
        run: ./gradlew check --info

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/test-results/*/*.xml'

#      - name: Junit Report
#        uses: allegro-actions/junit-reporter@v1
#        if: ${{ success() || failure() }}
#        with:
#          path: '**/test-results/*/*.xml'
